"""
Notifications resource for Upsales API.

Provides read-only access to system-generated notifications about CRM activities.
Notifications cannot be created, updated, or deleted via the API.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import builtins

    from upsales.http import HTTPClient

from upsales.models.notifications import Notification


class NotificationsResource:
    """
    Read-only resource manager for system notifications.

    Notifications are automatically generated by Upsales when certain events occur,
    such as order updates, contact changes, and other important activities.

    This resource only supports GET operations - notifications cannot be created,
    updated, or deleted via the API.

    Example:
        ```python
        # Get a specific notification
        notification = await upsales.notifications.get(1)
        print(f"Type: {notification.type}")
        print(f"Message: {notification.message}")

        # List all notifications (usually empty in production)
        notifications = await upsales.notifications.list()
        for notif in notifications:
            print(f"{notif.id}: {notif.message}")

        # Get all notifications with auto-pagination
        all_notifications = await upsales.notifications.list_all()
        ```

    Note:
        The list endpoint typically returns an empty array in most environments.
        Individual notifications can be accessed directly by ID if you know the ID.
    """

    def __init__(self, http: HTTPClient):
        """
        Initialize notifications resource.

        Args:
            http: HTTP client for API requests.
        """
        self._http = http
        self._endpoint = "/notifications"

    async def get(self, notification_id: int) -> Notification:
        """
        Fetch a single notification by ID.

        Args:
            notification_id: The notification ID.

        Returns:
            Notification object with full details.

        Raises:
            NotFoundError: If notification doesn't exist.
            AuthenticationError: If authentication fails.

        Example:
            ```python
            notification = await upsales.notifications.get(1)
            print(f"Created: {notification.date}")
            print(f"By: {notification.registeredBy.name}")
            ```
        """
        response = await self._http.get(f"{self._endpoint}/{notification_id}")
        data = response["data"]
        notification = Notification.model_validate(data)
        return notification

    async def list(
        self,
        limit: int = 100,
        offset: int = 0,
    ) -> list[Notification]:
        """
        List notifications with pagination.

        Note:
            This endpoint typically returns an empty array in most environments.
            Notifications are usually accessed directly by ID when needed.

        Args:
            limit: Maximum number of notifications to return (default: 100).
            offset: Number of notifications to skip (default: 0).

        Returns:
            List of Notification objects (typically empty).

        Raises:
            AuthenticationError: If authentication fails.

        Example:
            ```python
            # Get first page
            notifications = await upsales.notifications.list(limit=50)

            # Get second page
            more = await upsales.notifications.list(limit=50, offset=50)
            ```
        """
        response = await self._http.get(self._endpoint, limit=limit, offset=offset)
        data = response["data"]

        notifications = [Notification.model_validate(item) for item in data]
        return notifications

    async def list_all(self) -> builtins.list[Notification]:
        """
        Fetch all notifications with automatic pagination.

        Automatically handles pagination to retrieve all notifications.

        Note:
            This endpoint typically returns an empty array in most environments.
            Use with caution if you expect a large number of notifications.

        Returns:
            List of all Notification objects (typically empty).

        Raises:
            AuthenticationError: If authentication fails.

        Example:
            ```python
            all_notifications = await upsales.notifications.list_all()
            print(f"Total notifications: {len(all_notifications)}")
            ```
        """
        all_notifications: list[Notification] = []
        offset = 0
        limit = 100

        while True:
            batch = await self.list(limit=limit, offset=offset)
            if not batch:
                break

            all_notifications.extend(batch)
            offset += limit

        return all_notifications
