"""
Demo: TypedDict excludes frozen fields from autocomplete.

Shows how frozen fields like 'id' don't appear in IDE autocomplete.
"""

from typing import TypedDict, Unpack

from pydantic import BaseModel, Field


class UserUpdateFields(TypedDict, total=False):
    """
    Only updatable fields appear here.

    Notice: id, created_at, updated_at are EXCLUDED!
    This is what your IDE will suggest when you type user.edit(
    """

    name: str
    email: str
    administrator: int
    active: int
    # NO id field here! Won't show in autocomplete!


class User(BaseModel):
    """User model with frozen (read-only) fields."""

    # Frozen fields - can't be edited
    id: int = Field(frozen=True, description="Read-only: Auto-generated by server")
    created_at: str | None = Field(None, frozen=True, description="Read-only: Set by server")
    updated_at: str | None = Field(None, frozen=True, description="Read-only: Set by server")

    # Updatable fields
    name: str = Field(description="User's full name")
    email: str = Field(description="Email address")
    administrator: int = Field(description="Admin flag: 0 or 1")
    active: int = Field(1, description="Active status: 0 or 1")

    def to_update_dict(self, **overrides) -> dict:
        """Exclude frozen fields from update dict."""
        data = self.model_dump(exclude={"_client"})

        # Remove frozen fields
        for field_name, field_info in self.model_fields.items():
            if field_info.frozen:
                data.pop(field_name, None)

        data.update(overrides)
        return data

    async def edit(self, **kwargs: Unpack[UserUpdateFields]) -> "User":
        """
        Edit this user.

        IDE autocomplete shows ONLY updatable fields:
        - name: str
        - email: str
        - administrator: int
        - active: int

        IDE autocomplete does NOT show read-only fields:
        - id (frozen)
        - created_at (frozen)
        - updated_at (frozen)

        Example:
            >>> user = await client.users.get(1)
            >>>
            >>> # Try typing: await user.edit(
            >>> # Your IDE suggests: name, email, administrator, active
            >>> # Your IDE does NOT suggest: id, created_at, updated_at
            >>>
            >>> await user.edit(
            ...     name="Jane Doe",
            ...     email="jane@example.com"
            ... )
            >>>
            >>> # This would be a type error (id not in UserUpdateFields):
            >>> # await user.edit(id=999)  # ❌ Type checker catches this!
        """
        # In real implementation, would update via API
        # For demo, just return self
        return self


async def demo():
    """Demo showing frozen fields excluded from autocomplete."""

    user = User(
        id=1,
        created_at="2024-01-01T00:00:00Z",
        updated_at="2024-01-01T00:00:00Z",
        name="John Doe",
        email="john@example.com",
        administrator=0,
        active=1,
    )

    print("User created:")
    print(f"  ID: {user.id} (frozen)")
    print(f"  Name: {user.name}")
    print(f"  Email: {user.email}")
    print()

    # ✅ GOOD: Only updatable fields
    print("✅ This works - updatable fields only:")
    await user.edit(
        name="Jane Doe",  # ✅ IDE suggests this
        email="jane@example.com",  # ✅ IDE suggests this
        administrator=1,  # ✅ IDE suggests this
    )
    print("  Updated name, email, administrator")
    print()

    # ❌ BAD: Trying to update frozen fields
    print("❌ Type checker would catch these errors:")
    print("  await user.edit(id=999)  # ❌ 'id' not in UserUpdateFields")
    print("  await user.edit(created_at='...')  # ❌ Not in UserUpdateFields")
    print()

    # Even if someone bypasses type checking, to_update_dict() protects:
    print("✅ Runtime protection with to_update_dict():")
    update_dict = user.to_update_dict(id=999, name="Jane")
    print("  Input: id=999, name='Jane'")
    print(f"  Output: {update_dict}")
    print("  Notice: 'id' is excluded! ✅")
    print()

    # Show what fields are frozen
    print("📋 Field types:")
    for field_name, field_info in User.model_fields.items():
        status = "🔒 FROZEN (read-only)" if field_info.frozen else "✏️  UPDATABLE"
        print(f"  {field_name}: {status}")


if __name__ == "__main__":
    import asyncio

    asyncio.run(demo())

    print()
    print("=" * 60)
    print("TRY THIS IN YOUR IDE:")
    print("=" * 60)
    print("1. Create a User instance")
    print("2. Type: await user.edit(")
    print("3. Your IDE will ONLY suggest:")
    print("   - name")
    print("   - email")
    print("   - administrator")
    print("   - active")
    print("4. Your IDE will NOT suggest:")
    print("   - id")
    print("   - created_at")
    print("   - updated_at")
    print("=" * 60)
